-- ============================================================================
-- 08 — Storage policies pro bucket `idemaq-privado` (foto da coleta da OS)
--
-- ⚠️ ATENÇÃO: storage.objects é uma tabela do schema do Supabase. Comandos
-- ALTER/CREATE POLICY direto em storage.objects estouram com:
--     ERROR: 42501: must be owner of table objects
-- porque o dono dessa tabela é o role `supabase_storage_admin` (interno).
--
-- CAMINHO QUE FUNCIONA — criar policies pela UI do Dashboard:
--   https://supabase.com/dashboard/project/yfbbruxqfzgetapbvrgd/storage/policies
--   → New policy → For full customization
--   Criar 4 policies com bucket_id='idemaq-privado', role=authenticated:
--
--   1. SELECT — "idemaq_privado_select"
--        USING:      bucket_id = 'idemaq-privado'
--
--   2. INSERT — "idemaq_privado_insert"
--        WITH CHECK: bucket_id = 'idemaq-privado'
--
--   3. UPDATE — "idemaq_privado_update"
--        USING:      bucket_id = 'idemaq-privado'
--        WITH CHECK: bucket_id = 'idemaq-privado'
--
--   4. DELETE — "idemaq_privado_delete"
--        USING:      bucket_id = 'idemaq-privado'
--
-- TESTE RÁPIDO antes de criar policies: muitas vezes o Supabase já permite
-- as operações pra usuários `authenticated` por default em buckets privados.
-- Testar primeiro fazendo upload no app — se funcionar, não precisa criar
-- as 4 policies acima. Se der "row violates row-level security policy" ou
-- "403 Unauthorized", aí sim crie as policies pela UI.
--
-- PRÉ-REQUISITO (manual, 1 vez):
--   No Supabase Dashboard → Storage → New bucket
--     Nome:    idemaq-privado
--     Public:  OFF (privado)
--     Click "Create bucket"
--   ✅ JÁ FOI FEITO em 20/05/2026 (terminal `geral` ou outro).
-- ============================================================================

-- Nenhum SQL pra rodar aqui — usar UI do Dashboard conforme instrução acima.
SELECT '08-storage-os-coleta: usar UI do Dashboard, ver comentario do arquivo' AS instrucao;
